export const getWeatherDescription = (weatherCode,isDay) => {
    const lookup={
        "00":[require("../assets/weather-icons/SVG/day_clear.svg"),"Cloud development not observed or not observable"],
        "01":[require("../assets/weather-icons/SVG/day_clear.svg"),"	Clouds generally dissolving or becoming less developed"],
        "02":[require("../assets/weather-icons/SVG/day_clear.svg"),"State of sky on the whole unchanged"],
        "03":[require("../assets/weather-icons/SVG/day_clear.svg"),"Clouds generally forming or developing"],
        "04":[require("../assets/weather-icons/SVG/angry_clouds.svg"),"Visibility reduced by smoke, e.g. veldt or forest fires, industrial smoke or volcanic ashes"],
        "05":[require("../assets/weather-icons/SVG/day_clear.svg"),"Haze"],
        "06":[require("../assets/weather-icons/SVG/day_clear.svg"),"Widespread dust in suspension in the air, not raised by wind at or near the station at the time of observation"],
        "07":[require("../assets/weather-icons/SVG/day_clear.svg"),"Dust or sand raised by wind at or near the station at the time of observation, but no well-developed dust whirl(s) or sand whirl(s), and no duststorm or sandstorm seen; or, in the case of ships, blowing spray at the station"],
        "08":[require("../assets/weather-icons/SVG/day_clear.svg"),"Well-developed dust whirl(s) or sand whirl(s) seen at or near the station during the preceding hour or at the time of observation, but no duststorm or sandstorm"],
        "09":[require("../assets/weather-icons/SVG/day_clear.svg"),"Duststorm or sandstorm within sight at the time of observation, or at the station during the preceding hour"],
        "10":[require("../assets/weather-icons/SVG/mist.svg"),"Mist"],
        "11":[require("../assets/weather-icons/SVG/mist.svg"),"Patchy shallow fog or ice fog at the station, whether on land or sea, not deeper than about 2 metres on land or 10 metres at sea"],
        "12":[require("../assets/weather-icons/SVG/mist.svg"),"More or less continuous shallow fog or ice fog at the station, whether on land or sea, not deeper than about 2 metres on land or 10 metres at sea, covering less than half the sky"],
        "13":[require("../assets/weather-icons/SVG/thunder.svg"),"Lightning visible, no thunder heard"],
        "14":[require("../assets/weather-icons/SVG/day_clear.svg"),"Precipitation within sight, not reaching the ground or the surface of the sea"],
        "15":[require("../assets/weather-icons/SVG/day_clear.svg"),"Precipitation within sight, reaching the ground or the surface of the sea, but distant, i.e. estimated to be more than 5 km from the station"],
        "16":[require("../assets/weather-icons/SVG/day_clear.svg"),"Precipitation within sight, reaching the ground or the surface of the sea, near to, but not at the station"],
        "17":[require("../assets/weather-icons/SVG/thunder.svg"),"Thunderstorm, but no precipitation at the time of observation"],
        "18":[require("../assets/weather-icons/SVG/thunder.svg"),"Squalls at or within sight of the station during the preceding hour or at the time of observation"],
        "19":[require("../assets/weather-icons/SVG/tornado.svg"),"Funnel cloud(s) at or within sight of the station during the preceding hour or at the time of observation, not connected with a thunderstorm"],
        "20":[require("../assets/weather-icons/SVG/day_clear.svg"),"Drizzle (not freezing) or snow grains, not falling as shower(s) and not reaching the ground"],
        "21":[require("../assets/weather-icons/SVG/day_clear.svg"),"Rain (not freezing), not falling as shower(s) and not reaching the ground"],
        "22":[require("../assets/weather-icons/SVG/day_clear.svg"),"Snow, not falling as shower(s) and not reaching the ground"],
        "23":[require("../assets/weather-icons/SVG/day_clear.svg"),"Rain and snow, not falling as shower(s) and not reaching the ground"],
        "24":[require("../assets/weather-icons/SVG/day_clear.svg"),"Freezing drizzle or freezing rain, not falling as shower(s) and not reaching the ground"],
        "25":[require("../assets/weather-icons/SVG/day_clear.svg"),"Shower(s) of rain alone"],
        "26":[require("../assets/weather-icons/SVG/day_clear.svg"),"Shower(s) of rain and snow or hail"],
        "27":[require("../assets/weather-icons/SVG/day_clear.svg"),"Shower(s) of hail,or rain and hail"],
        "28":[require("../assets/weather-icons/SVG/day_clear.svg"),"Fog or Ice fog in whole or part"],
        "29":[require("../assets/weather-icons/SVG/thunder.svg"),"Thunderstorm with or without precipitation"],
        "30":[require("../assets/weather-icons/SVG/day_clear.svg"),"Slight or moderate duststorm or sandstorm has decreased during the preceding hour"],
        "31":[require("../assets/weather-icons/SVG/day_clear.svg"),"Slight or moderate duststorm or sandstorm, no appreciable change during the preceding hour"],
        "32":[require("../assets/weather-icons/SVG/day_clear.svg"),"Slight or moderate duststorm or sandstorm has begun or has increased during the preceding hour"],
        "33":[require("../assets/weather-icons/SVG/day_clear.svg"),"Severe duststorm or sandstorm has decreased during the preceding hour"],
        "34":[require("../assets/weather-icons/SVG/day_clear.svg"),"Severe duststorm or sandstorm, no appreciable change during the preceding hour"],
        "35":[require("../assets/weather-icons/SVG/day_clear.svg"),"Severe duststorm or sandstorm has begun or has increased during the preceding hour"],
        "36":[require("../assets/weather-icons/SVG/day_clear.svg"),"Slight or moderate drifting snow has decreased during the preceding hour"],
        "37":[require("../assets/weather-icons/SVG/day_clear.svg"),"Slight or moderate drifting snow, no appreciable change during the preceding hour"],
        "38":[require("../assets/weather-icons/SVG/snow.svg"),"Slight or moderate drifting snow has begun or has increased during the preceding hour"],
        "39":[require("../assets/weather-icons/SVG/snow.svg"),"Heavy drifting snow has decreased during the preceding hour"],
        "40":[require("../assets/weather-icons/SVG/fog.svg"),"Fog or ice fog at a distance at the time of observation, but not at the station during the preceding hour, the fog or ice fog extending to a level above that of the observer"],
        "41":[require("../assets/weather-icons/SVG/fog.svg"),"Fog or ice fog in patches"],
        "42":[require("../assets/weather-icons/SVG/fog.svg"),"Fog or ice fog, sky visible, has become thinner during the preceding hour"],
        "43":[require("../assets/weather-icons/SVG/fog.svg"),"Fog or ice fog, sky invisible, has become thinner during the preceding hour"],
        "44":[require("../assets/weather-icons/SVG/fog.svg"),"Fog or ice fog, sky visible, no appreciable change during the preceding hour"],
        "45":[require("../assets/weather-icons/SVG/fog.svg"),"Fog or ice fog, sky invisible, no appreciable change during the preceding hour"],
        "46":[require("../assets/weather-icons/SVG/fog.svg"),"Fog or ice fog, sky visible, has begun or has become thicker during the preceding hour"],
        "47":[require("../assets/weather-icons/SVG/fog.svg"),"Fog or ice fog, sky invisible, has begun or has become thicker during the preceding hour"],
        "48":[require("../assets/weather-icons/SVG/fog.svg"),"Fog, depositing rime, sky visible"],
        "49":[require("../assets/weather-icons/SVG/fog.svg"),"Fog, depositing rime, sky invisible"],
        "50":[require("../assets/weather-icons/SVG/mist.svg"),"Drizzle, not freezing, intermittent, slight at time of observation"],
        "51":[require("../assets/weather-icons/SVG/mist.svg"),"Drizzle, not freezing, continuous, slight at time of observation"],
        "52":[require("../assets/weather-icons/SVG/mist.svg"),"Drizzle, not freezing, intermittent, moderate at time of observation"],
        "53":[require("../assets/weather-icons/SVG/mist.svg"),"Drizzle, not freezing, continuous, moderate at time of observation"],
        "54":[require("../assets/weather-icons/SVG/mist.svg"),"Drizzle, not freezing, intermittent, heavy at time of observation"],
        "55":[require("../assets/weather-icons/SVG/mist.svg"),"Drizzle, not freezing, continuous, heavy at time of observation"],
        "56":[require("../assets/weather-icons/SVG/mist.svg"),"Drizzle, freezing, slight"],
        "57":[require("../assets/weather-icons/SVG/sleet.svg"),"Drizzle, freezing, moderate or heavy"],
        "58":[require("../assets/weather-icons/SVG/rain.svg"),"Drizzle and rain, slight"],
        "59":[require("../assets/weather-icons/SVG/rain.svg"),"Drizzle and rain, moderate or heavy"],
        "60":[require("../assets/weather-icons/SVG/rain.svg"),"Rain, not freezing, intermittent, slight at time of observation"],
        "61":[require("../assets/weather-icons/SVG/rain.svg"),"Rain, not freezing, continuous, slight at time of observation"],
        "62":[require("../assets/weather-icons/SVG/rain.svg"),"Rain, not freezing, intermittent, moderate at time of observation"],
        "63":[require("../assets/weather-icons/SVG/rain.svg"),"Rain, not freezing, continuous, moderate at time of observation"],
        "64":[require("../assets/weather-icons/SVG/rain.svg"),"Rain, not freezing, intermittent, heavy at time of observation"],
        "65":[require("../assets/weather-icons/SVG/rain.svg"),"Rain, not freezing, continuous, heavy at time of observation"],
        "66":[require("../assets/weather-icons/SVG/rain.svg"),"Rain, freezing, slight"],
        "67":[require("../assets/weather-icons/SVG/rain.svg"),"Rain, freezing, moderate or heavy"],
        "68":[require("../assets/weather-icons/SVG/snow.svg"),"Rain or drizzle and snow, slight"],
        "69":[require("../assets/weather-icons/SVG/snow.svg"),"Rain or drizzle and snow, moderate or heavy"],
        "70":[require("../assets/weather-icons/SVG/snow.svg"),"Intermittent fall of snowflakes, slight at time of observation"],
        "71":[require("../assets/weather-icons/SVG/snow.svg"),"Continuous fall of snowflakes, slight at time of observation"],
        "72":[require("../assets/weather-icons/SVG/snow.svg"),"Intermittent fall of snowflakes, moderate at time of observation"],
        "73":[require("../assets/weather-icons/SVG/snow.svg"),"Continuous fall of snowflakes, moderate at time of observation"],
        "74":[require("../assets/weather-icons/SVG/snow.svg"),"Intermittent fall of snowflakes, heavy at time of observation"],
        "75":[require("../assets/weather-icons/SVG/snow.svg"),"Continuous fall of snowflakes, heavy at time of observation"],
        "76":[require("../assets/weather-icons/SVG/snow.svg"),"Diamond dust (with or without fog) at time of observation"],
        "77":[require("../assets/weather-icons/SVG/snow.svg"),"Snow grains (with or without fog) at time of observation"],
        "78":[require("../assets/weather-icons/SVG/snow.svg"),"Isolated star-like snow crystals (with or without fog) at time of observation"],
        "79":[require("../assets/weather-icons/SVG/snow.svg"),"Ice pellets"],
        "80":[require("../assets/weather-icons/SVG/rain.svg"),"Rain shower(s), slight"],
        "81":[require("../assets/weather-icons/SVG/rain.svg"),"Rain shower(s), moderate or heavy"],
        "82":[require("../assets/weather-icons/SVG/rain.svg"),"Rain shower(s), violent"],
        "83":[require("../assets/weather-icons/SVG/sleet.svg"),"Showers of rain and snow mixed, slight"],
        "84":[require("../assets/weather-icons/SVG/sleet.svg"),"Showers of rain and snow mixed, moderate or heavy"],
        "85":[require("../assets/weather-icons/SVG/snow.svg"),"Snow shower(s), slight"],
        "86":[require("../assets/weather-icons/SVG/snow.svg"),"Snow shower(s), moderate or heavy"],
        "87":[require("../assets/weather-icons/SVG/snow.svg"),"Shower(s) of snow pellets or small hail, with or without rain or rain and snow mixed, slight"],
        "88":[require("../assets/weather-icons/SVG/snow.svg"),"Shower(s) of snow pellets or small hail, with or without rain or rain and snow mixed, moderate or heavy"],
        "89":[require("../assets/weather-icons/SVG/snow.svg"),"Shower(s) of hail, with or without rain or rain and snow mixed, not associated with thunder, slight"],
        "90":[require("../assets/weather-icons/SVG/snow.svg"),"Shower(s) of hail, with or without rain or rain and snow mixed, not associated with thunder, moderate or heavy"],
        "91":[require("../assets/weather-icons/SVG/rain_thunder.svg"),"Slight rain at time of observation"],
        "92":[require("../assets/weather-icons/SVG/rain_thunder.svg"),"Moderate rain at time of observation"],
        "93":[require("../assets/weather-icons/SVG/snow_thunder.svg"),"Slight snow or rain and snow mixed or hail at time of observation"],
        "94":[require("../assets/weather-icons/SVG/snow_thunder.svg"),"Moderate or heavy snow or rain and snow mixed or hail at time of observation"],
        "95":[require("../assets/weather-icons/SVG/snow_thunder.svg"),"Thunderstorm, slight or moderate, without hail, but with rain and/or snow at time of observation"],
        "96":[require("../assets/weather-icons/SVG/snow_thunder.svg"),"Thunderstorm, slight or moderate, with hail at time of observation"],
        "97":[require("../assets/weather-icons/SVG/snow_thunder.svg"),"Thunderstorm, heavy, without hail, but with rain and/or snow at time of observation"],
        "98":[require("../assets/weather-icons/SVG/snow_thunder.svg"),"Thunderstorm combined with duststorm or sandstorm at time of observation"],
        "99":[require("../assets/weather-icons/SVG/snow_thunder.svg"),"Thunderstorm, heavy, with hail at time of observation"]
    }
    return lookup[weatherCode.toString().padStart(2,"0")];
}
